import { useEffect, useState } from "react";
import '../styles/globals.css'
import 'bootstrap/dist/css/bootstrap.css'
import Head from 'next/head'
import Router from 'next/router';



function MyApp({ Component, pageProps }) {


  const [loading, setLoading] = useState(true);


  useEffect(() => {
    require('bootstrap/dist/js/bootstrap');


    Router.events.on("routeChangeStart", () => setLoading(true));
    Router.events.on("routeChangeComplete", () => setLoading(false));
    Router.events.on("routeChangeError", () => setLoading(false));
    window.addEventListener("load", function () { setLoading(false); });
  }, []);



  return (
    <>
      <Head>
        <title>MoviesFree</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Component {...pageProps} loading={loading} />

    </>
  );
}

export default MyApp
